### PR TITLE
Mg/18 basic layout

### PR DESCRIPTION
**Pull request by allthesignals**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
~- [ ] Tests for the changes have been added (for bug fixes / features)~
~- [ ] Docs have been added / updated (for bug fixes / features)~

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Addresses #18 by adding a basic [grid layout](https://tailwindcss.com/docs/grid-row#spanning-rows)  

* **What is the current behavior?** (You can also link to an open issue here)
No grid!

* **What is the new behavior (if this is a feature change)?**
image

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Nope!

* **Other information**:
image

### CODE REVIEW

**Comment by allthesignals** [comment]
> * In `global.css`: What are the advantages to adding background and text styles here, as opposed to inline tailwind `className`s on the `_app.tsx` component, or even the `DefaultLayout.tsx` component?

Oh, I'm not sure. Either force of habit or path of least resistence. I just couldn't find the HTML file where this stuff was rendered and did it there instead. Should go somewhere else instead but both work fine.


> * In `DefaultLayout.tsx`: What is the purpose for making `<footer>` a child of `<main>` instead of leaving it as the next sibling?

I think this is how the grid layout for the design is made. The "header" is really the nav panel to the left. Main is the to the right. The footer should go below whatever content is rendered in main (or so it seemed to me). Basically I tried to mirror the structure of the tags with the design and used whichever tags were semantically most appropriate.

**Comment by zenlex** [comment]
I think Matt's assessment of the intended layout is correct but I'm not crazy about the tag breakdown either. We could use <aside> or <nav> for the sidebar, <main> or <section> for the center content area. We could have a <header><nav><footer> breakdown inside an <aside> or <section> tag for the sidebar also as an option. With the way it plays on mobile v/desktop I'm inclined to think the sidebar as a <nav> tag with 3 <sections> in it or a <header><section><footer> inside it is the way to go with <main> being reserved for the main content section which currently has no footer in the design. (which can be revisited). If the main page area needs a footer I'd suggest a <section> for the grid space with a <header><main><footer> breakdown inside it, or <main> with <header><section><footer>. If anybody's got good screenreader chops who wants to chime in on that feel free.

**Comment by alecvision** [comment]
Just saw your comment @zenlex. You make an excellent point about the screen-reader experience.

**Comment by allthesignals** [comment]
Okay! All great points.

I would just err on the side of getting work merged (within reason) and then opening follow-up issues.

**Review by alecvision — APPROVED** [review]
Awesome 🎉

**Comment by allthesignals** [comment]
I think to distill some of @zenlex points into action items for now or later:

1. Prefer semantic <nav> tag over current use of <header>. Use <header><nav><footer> breakdown inside an <nav> (or <aside>?).
2. If the main page area needs a footer, prefer a <section> tag.
3. Investigate implications for screenreaders.

**Comment by zenlex** [comment]
@allthesignals you just did the same thing I did and didn't escape your html tags and comments parse markdown so it makes for very cryptic reading lol.

**Comment by zenlex** [comment]
The semantic tags we're talking about editing have no functional impact on layout and we shouldn't be referencing those element tags with css styles so we can do a more cohesive pass later. I would like to clean that bit up earlier in the process to set some precedents as we build more, but the accessibility review can happen much later

**Review by NicoleJaneway — APPROVED** [review]
lgtm!  I used this as the base branch for mine (feature/nav).

**Pull request merged**
