### PR TITLE
Issue #81, Initial migration of WP blogs to md

### PR DESCRIPTION
**Pull request by zenlex**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by zenlex** [comment]
Shout out to @higherkey for getting this wordpress conversion done. I spot checked a few of the MD files and it looks good. We'll want to do a full pass through the blogs with @chimchim237 once we get it deployed to staging to make any needed tweaks. Currently marked PR as on hold while @alecvision finishes up the MD parser refactor as the currently published version will break staging if I add the new markdown files. Once we've got Alec's new plugin deployed we'll merge these in as test material.

**Comment by higherkey** [comment]
One thing, the housekeeping branch that I published has a duplicate folder with all the files again. Should I remove all the duplicate stuff?

Also, we should specifically take a look at the images. The script attempted to grab images but I don't know how well it worked.

**Comment by zenlex** [comment]
This will need someone to go through and fix frontmatter to conform to the schema in #113 and then should be good to merge.

**Comment by zenlex** [comment]
went through blogs and commented out or removed broken image links to allow it to build. Blog needs editorial review and then repair of any broken images deemed necessary.

**Pull request merged**
